/**
 * Report Generator — produces bug bounty submission reports from engagement data.
 */

export class ReportGenerator {
  #evidenceChain;
  #coverageLedger;

  constructor({ evidenceChain, coverageLedger }) {
    this.#evidenceChain = evidenceChain;
    this.#coverageLedger = coverageLedger;
  }

  generateMarkdown(engagement, findings, sopId) {
    const evidence = this.#evidenceChain ? this.#evidenceChain.recent(200) : [];
    const coverage = sopId && this.#coverageLedger ? this.#coverageLedger.getStatus(sopId) : { percentage: 0, completed: 0, total: 0 };

    const sev = (s) => findings.filter(f => f.severity === s).length;

    const lines = [
      "# Security Assessment Report",
      "",
      "## Engagement Details",
      `- **Target:** ${engagement.target || "unknown"}`,
      `- **Scope:** ${JSON.stringify(engagement.scope || [])}`,
      `- **Operator:** ${engagement.operatorId || "unknown"}`,
      `- **Date:** ${new Date().toISOString().split("T")[0]}`,
      `- **Methodology Coverage:** ${coverage.percentage}% (${coverage.completed}/${coverage.total} steps)`,
      "",
      "## Executive Summary",
      `- Total findings: ${findings.length}`,
      `- Critical: ${sev("critical")}`,
      `- High: ${sev("high")}`,
      `- Medium: ${sev("medium")}`,
      `- Low: ${sev("low")}`,
      `- Informational: ${sev("info")}`,
      "",
      "## Findings",
      "",
    ];

    for (const f of findings) {
      lines.push(`### ${f.title}`);
      lines.push(`- **Severity:** ${(f.severity || "info").toUpperCase()}`);
      lines.push(`- **Target:** ${f.target || "unknown"}`);
      if (f.description) lines.push(`- **Description:** ${f.description}`);
      if (f.reproduction) {
        lines.push("- **Reproduction:**");
        lines.push("\`\`\`");
        lines.push(f.reproduction);
        lines.push("\`\`\`");
      }
      if (f.impact) lines.push(`- **Impact:** ${f.impact}`);
      if (f.remediation) lines.push(`- **Remediation:** ${f.remediation}`);
      lines.push("");
    }

    lines.push("## Evidence Chain");
    lines.push(`Total entries: ${evidence.length}`);
    lines.push("Integrity: SHA-256 hash-chained");
    lines.push("");
    lines.push("---");
    lines.push("*Generated by Edge AIDE Cybersecurity Workbench*");

    return lines.join("\n");
  }

  generateJSON(engagement, findings, sopId) {
    return JSON.stringify({
      report: {
        generatedAt: new Date().toISOString(),
        engagement,
        findings,
        coverage: this.#coverageLedger?.getStatus(sopId),
        evidenceCount: this.#evidenceChain?.count || 0,
      },
    }, null, 2);
  }
}